# Data Cleaning and Data Tranformations 

**Befor data cleaning, we have to explore the data (Data Exploration)**
- We observe the data given to us
- we observe the problems

**In data exploration we need to observer below points**

- Wrong data
- Wrong data type
- Duplicates
- Missing values
- abnormal data (outliers)
- unimportant columns

**after data exploration we will apply data cleaning on problems**

- Based on the problems in data and also based on bussiness problem we have to apply data cleaning accordingly 
- in data cleaning, we have various options to deal
**- we need to give the report what and why we have done the in data cleaning**
- Each dataset has different problems and each project different ways to solve the problems
- entire data cleaning will be dependent on bussiness problem and data
- before proceeding to data cleaning, 1 should have cleare idea about your bussiness problem with 2 what should observe in data exploration
  

**Below is the solution use in data clearning**
- wrong data  = replace or remove
- wrong data type = convert
- duplicates = remove or retain (keep as it is)
- missing values = replace or remove
- abnormal data (outliers) = replace or remove or retain
- unimportant columns = remove


**What is outlier ?**
- the data points which are distant or wich are far away from other data points

reason for outliers ?
- wrong data entry
- technical error
- real values




# Data cleaning for structured data

- for every data cleaning step we have 3 options, out of which we have select any 1

1) Replace
   - replace with original data by contacting backend team (best solution)
   - replace with statistically
     1) numerical column : replace with mean
     2) text/categorical column : replace with mode (most repeated) 
2) Remove
   wrong data less than 5% we can remove above data we required approval and justification and not recomanded 

3) retain (keep as it is)

**code for the cleaning**

1) replace
    - df.loc[] = new value

2) remove
    - df.drop(index=[])
    - df.drop(columns=[]) 

3) convert
    - df['col'].astype(datatype)

4) remove duplicates 
    - df.drop_duplicates()

5) replace missing values
    - df['col'].fillna(value)



In [1]:
import numpy as np
import pandas as pd

In [2]:
s = {'studentid':[101,101,103,104,105,105,107,108,109], 'age':[24,26,np.nan,'srk',15,15,20,'20.6','19.4']}
studant_data = pd.DataFrame(s)
studant_data

,studentid,age
0,101,24
1,101,26
2,103,NaN
3,104,srk
4,105,15
5,105,15
6,107,20
7,108,20.6
8,109,19.4


# Data Exploration 

In [8]:
studant_data.shape

(9, 2)

**observe datatype of each colum**

In [7]:
studant_data.dtypes

studentid     int64
age          object
dtype: object

**Observation 1**
- **As observe in the table there are two columns one is studentid and age, but here the datatype of age column is showing object in place of float which is not correct.**

In [9]:
studant_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   studentid  9 non-null      int64 
 1   age        8 non-null      object
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes


**observation 2** 
- there are 9 rows and 2 columns in this dataframe.
- **age column data type is showing object but as per data it should be float**
- **in age column 8 values are there but dataframe have 9 rows means one value is missing**

In [3]:
studant_data['studentid'].unique()

array([101, 103, 104, 105, 107, 108, 109])

In [4]:
studant_data['age'].unique()

array([24, 26, nan, 'srk', 15, 20, '20.6', '19.4'], dtype=object)

**observation 3**

- **here some values are object datatype in place of float in age column**

In [5]:
l = []
for i in studant_data['age'].unique().tolist():
    if type(i) not in [int,float]:
        l.append(i)
l

['srk', '20.6', '19.4']

In [14]:
studant_data[studant_data['age'].isin(l)]

,studentid,age
3,104,srk
7,108,20.6
8,109,19.4


In [13]:
studant_data[studant_data['age'].isin(l)].shape[0]

3

In [8]:
studant_data[studant_data['age'].isin(l)]['studentid'].tolist()

[104, 108, 109]

**Observation 4**

- **above are the 3 wrong data type values are there in the age column having 104,108,109 studentid**

In [10]:
studant_data[studant_data.duplicated()]

,studentid,age
5,105,15


**Observation 5**
- **the data with student id 105 has duplicat data**

In [22]:
studant_data.isnull().sum()

studentid    0
age          1
dtype: int64

In [23]:
studant_data[studant_data['age'].isnull()]

,studentid,age
2,103,NaN


**Observation 6**

- **there is one missing value in the 2nd row with student id 103**

- there are 6 observation is done on the dataframe and as per observation we have below points which required tratment
1) one missing value in the 2nd column
2) one value is wrong 3rd row age column
3) two datatype are wrong in 7th and 8th row age column
4) duplicate value in 5th row

In [15]:
# Data treatment 

**1) one missing value in the 2nd column**

- for this we can apply two solutions, remove or replace 


option 1 : remove the missing values

In [27]:
studant_data.drop(index=[2])

,studentid,age
0,101,24
1,101,26
3,104,srk
4,105,15
5,105,15
6,107,20
7,108,20.6
8,109,19.4


option 2 : replace the missing values

In [34]:
# if u want to replace all missing values in the given column with single value like mean.

studant_data['age']=studant_data['age'].fillna(23)

In [31]:
# if u want to replace all missing values in the given column with different values.

#studant_data.loc[] = []

**2) one value is wrong 3rd row age column**

- here we have two option we can replace the value with original data or mean or we can remove the value

In [45]:
studant_data.loc[3]['age']

'srk'

option 1 : remove the value


overall wrong data is less than 5% after treatment so we can drop it 

In [46]:
studant_data.drop(index=3)

,studentid,age
0,101,24
1,101,26
2,103,23
4,105,15
5,105,15
6,107,20
7,108,20.6
8,109,19.4


option 2: replce with mean or original data 

In [48]:
studant_data.loc[3,'age'] = 23
studant_data

,studentid,age
0,101,24
1,101,26
2,103,23
3,104,23
4,105,15
5,105,15
6,107,20
7,108,20.6
8,109,19.4


**3) two datatype are wrong in 7th and 8th row age column**

- here we can change the data type of the column to float as all the values is int or float

In [49]:
studant_data['age'].unique()

array([24, 26, 23, 15, 20, '20.6', '19.4'], dtype=object)

In [50]:
studant_data['age'].astype(float)
studant_data

,studentid,age
0,101,24
1,101,26
2,103,23
3,104,23
4,105,15
5,105,15
6,107,20
7,108,20.6
8,109,19.4


**4) duplicate value in 5th row**

- here we have option to drop the data as it is exact duplicate 

In [52]:
studant_data[studant_data.duplicated()]

,studentid,age
5,105,15


In [57]:
studant_data = studant_data.drop_duplicates()

# final DataFrame after Data Treatment 

In [58]:
studant_data

,studentid,age
0,101,24
1,101,26
2,103,23
3,104,23
4,105,15
6,107,20
7,108,20.6
8,109,19.4
